# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-24.04"
  tools:
    python: 3.9

build:

  os: ubuntu-22.04

  tools:

    python: "3.10"

# Optionally build your docs in additional formats such as PDF
# formats:
# - pdf

# specify dependencies
python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs
