# Required
version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.10"

# specify dependencies
python:
  version: "3.9"
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs
